n1 = int(input('Número 01: '))
n2 = int(input('Número 02: '))
n3 = int(input('Número 03: '))
m = max(n1, n2, n3)
min = min(n1, n2, n3)
print('O maior número é {}'.format(m))
print('O menor número é {}'.format(min))